import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* children : page.tsx에 있는 컴포넌트들이 들어오게 됨 */}
      <body className={inter.className}>
        <nav>
          <Link href={"/"} >
            Home
          </Link>&nbsp;&nbsp;
          <Link href={"/posts"}>
            Post
          </Link>
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
